services:
  - type: web
    name: mutual-fund-rag-api
    runtime: python
    buildCommand: >
      pip install -r requirements.txt &&
      HF_HOME=/opt/render/project/src/.hf_cache
      python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: CHROMA_API_KEY
        sync: false
      - key: CHROMA_TENANT
        sync: false
      - key: CHROMA_DATABASE
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_MODEL
        value: llama-3.3-70b-versatile
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: HF_HOME
        value: /opt/render/project/src/.hf_cache
      - key: SENTENCE_TRANSFORMERS_HOME
        value: /opt/render/project/src/.hf_cache
